dataset_root: 'datasets'
dataset_name: 'ENZYMES'
random_split_flag: True
data_split_ratio: [0.8, 0.1, 0.1]
seed: 2
data_explain_cutoff: -1
budget: 10
threshold: 0.05
gamma: 1
radium: 0.05
k: 5
bounds: [0, 0, 0, 0, 0, 0, 0, 0, 8, 12, 0, 0]
num_classes: 6