dataset_root: 'datasets'
dataset_name: 'PROTEINS'
random_split_flag: True
data_split_ratio: [0.7, 0.1, 0.2]
seed: 2
data_explain_cutoff: -1
budget: 100
threshold: 0.06
gamma: 1
radium: 0.05
k: 5
bounds: [98, 102, 0, 0]
num_classes: 2